import "ol/ol.css";
import "./css/controlsReset.css";
import "./css/drawsReset.css";
import { map } from "./pages/1-loadMap/loadMap";
import addControls from "./pages/2-addControls/addControls";
import showMutiSourceData from "./pages/3-showMutiSourceData/showMutiSource";
import drawShape from "./pages/4-drawShape/drawShape";
addControls();
showMutiSourceData();
drawShape();
map.setTarget("map");
